spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    url: jdbc:h2:tcp://localhost/~/boxtobox;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

  pid:
    file: /home/ec2-user/app/step2/capstone.pid

  profiles:
    include: oauth

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace



